language: c

compiler:
    - gcc

install:
    - sudo pip install cpp-coveralls --use-mirrors
    - sudo apt-get update -qq
    - sudo apt-get install -qq cmake

script:
    - cmake . -DCMAKE_C_FLAGS=--coverage -DCMAKE_CXX_FLAGS=--coverage
    - make
    - make test

after_success:
    - coveralls --exclude-pattern '.*CMake[^/]+\.c(?:pp)?'

notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/d4ac611092a6de1b9db4
        on_success: change  # options: [always|never|change] default: always
        on_failure: always  # options: [always|never|change] default: always
        on_start: false     # default: false
